routes/web.php
<?php


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SaveController;
use App\Http\Controllers\TasksController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\Admin\AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('auth.login');


});
 
Auth::routes();

Route::prefix('admin')->group(function() {

    Route::get('/dashboard', [AdminController::class, 'index']);
    Route::resource('projects', ProjectController::class);

    //tasks

    Route::controller(TasksController::class)->group(function() {
        
        Route::get('/project/{id}/tasks', 'index')->name('main');
        Route::post('/tasks/store', 'store');
        Route::get('/tasks/edit/{id}', 'edit');
        Route::put('/tasks/update/{id}', 'update');
        Route::get('/tasks/destroy/{id}', 'destroy');
        // Route::get('/mytasks', 'mytasks');
        Route::get('/mytasks', 'user_tasks');

    });

    Route::controller(SaveController::class)->group(function() {
   
        Route::put('/save/create/{id}', 'create');

    });

});




Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/admin/create.blade.php
<div class="modal-body py-lg-10 px-lg-10">

    <form action="{{ route('projects.store') }} " method="POST" enctype="multipart/form-data">
        @csrf

        <input type="text" name="name" class="form-control" placeholder="Loyiha Nomi">

        <textarea name="description" id="" cols="30" rows="3" class="form-control my-3"
            placeholder="Loyiha Tavsifi"></textarea>
        {{-- <textarea name="status" id="" cols="30" rows="3" class="form-control my-3" placeholder="Status"></textarea> --}}

        <input type="file" name="file" class="form-control my-3">

        <button type="submit" class="btn btn-danger">Ortga</button>
        <button type="submit" class="btn btn-primary">Saqlash</button>

    </form>

</div>

resources/views/admin/delete.blade.php
@extends('layouts.admin')

<div class="modal-body py-lg-10 px-lg-10">

    <form action="{{ route('projects.destroy',$project->id) }} " method="POST" enctype="multipart/form-data">
        @csrf

        <input type="text" name="name" class="form-control" placeholder="Name">

        <textarea name="description" id="" cols="30" rows="3" class="form-control my-3" placeholder="Description"></textarea>
        {{-- <textarea name="status" id="" cols="30" rows="3" class="form-control my-3" placeholder="Status"></textarea> --}}

        <input type="file" name="file" class="form-control my-3">

    <form action="{{route('projects.destroy',$project->id)}}" method="Post">
        @method('DELETE')
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
    </form>

</div>

resources/views/admin/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="col-md-12">

    <div class="row justify-content-center">

        <div class="col-md-7">

            <div class="card">

                <div class="card-header">
                    <div class="m-auto">
                        <h1>Loyihani Tahrirlash</h1>
                    </div>
                </div>
        
                <div class="card-body">
        
        
                    <form action="{{ route('projects.update',$project->id) }}" method="Post" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <input type="text" name="name" class="form-control" placeholder="Loyiha Nomi" value="{{ $project->name }}">
                
                        <textarea name="description" id="" cols="30" rows="3" class="form-control my-3" placeholder="Loyiha Tavsifi">{{ $project->description }}</textarea> 
                
                        <input type="file" name="file" class="form-control my-3">
                        <button class="btn btn-primary">Save</button>
                
                    </form>
        
                </div>
        
            </div>

        </div>

    </div>

</div>

@endsection

resources/views/admin/index.blade.php
@extends('layouts.admin')
@section('content')
    <div class="toolbar py-5 pt-lg-0" id="kt_toolbar">
        <!--begin::Container-->
        <div id="kt_toolbar_container" class="container-xxl d-flex flex-stack flex-wrap">
            <!--begin::Page title-->
            <div class="page-title d-flex flex-column me-3">
                <!--begin::Title-->
                <h1 class="d-flex text-gray-900 fw-bolder my-1 fs-3">Barcha Loyihalar</h1>

            </div>
            <!--end::Page title-->
            <!--begin::Actions-->
            <div class="d-flex align-items-center py-3 py-md-1">


                <div class="m-2">
                    Foydalanuvchi Ismi: <b class="fs-3 m-2">{{ auth()->user()->name }}</b>
                </div>
                <a href="{{ route('projects.create') }}" class="btn btn btn-dark" data-bs-toggle="modal"
                    data-bs-target="#kt_modal_create_app" id="kt_toolbar_primary_button">Yangi Loyiha</a>
                <!--end::Button-->
                     
                <div class="modal fade" id="kt_modal_create_app" tabindex="-1" aria-hidden="true">
                    <!--begin::Modal dialog-->
                    <div class="modal-dialog modal-dialog-centered mw-900px">
                        <!--begin::Modal content-->
                        <div class="modal-content">
                            <!--begin::Modal header-->
                            <div class="modal-header">
                                <!--begin::Modal title-->
                                <h2>Loyiha Yarating</h2>
                                <!--end::Modal title-->
                                <!--begin::Close-->
                                <div class="btn btn-sm btn-icon btn-active-color-primary" data-bs-dismiss="modal">
                                    <!--begin::Svg Icon | path: icons/duotune/arrows/arr061.svg-->
                                    <span class="svg-icon svg-icon-1">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                            viewBox="0 0 24 24" fill="none">
                                            <rect opacity="0.5" x="6" y="17.3137" width="16" height="2"
                                                rx="1" transform="rotate(-45 6 17.3137)" fill="currentColor" />
                                            <rect x="7.41422" y="6" width="16" height="2" rx="1"
                                                transform="rotate(45 7.41422 6)" fill="currentColor" />
                                        </svg>
                                    </span>
                                    <!--end::Svg Icon-->
                                </div>
                                <!--end::Close-->
                            </div>
                            <!--end::Modal header-->
                            <!--begin::Modal body-->
                            @include('admin.create')
                            <!--end::Modal body-->
                        </div>
                        <!--end::Modal content-->
                    </div>
                    <!--end::Modal dialog-->
                </div>
            </div>
            <!--end::Actions-->
        </div>
        <!--end::Container-->
    </div>

    <div id="kt_content_container" class="d-flex flex-column-fluid align-items-start container-xxl">

        <div class="content flex-row-fluid" id="kt_content">

            <div class="row g-6 g-xl-9">
                <!--begin::Col-->

                @foreach ($project as $item)
                    <div class="col-md-6 col-xl-4 my-2">

                        {{-- @if (auth()->user()->id == $item->user_id) --}}
                            <a href="/admin/project/{{ $item->id }}/tasks">
                        {{-- @endif --}}
                        
                        <!--begin::Card header-->
                        <div class="card border-hover-primary">
                            <div class="card-header border-0 pt-9">
                                <!--begin::Card Title-->
                                <div class="card-title m-0">
                                    <!--begin::Avatar-->
                                    <div class="symbol symbol-50px w-50px bg-light">
                                        <img src="{{ asset('storage/' . $item->file) }}" alt="image" class="" />
                                    </div>
                                    <!--end::Avatar-->

                                </div>
                            </div>


                            <div class="card-body p-9">


                                <!--begin::Name-->
                                <div class="fs-3 fw-bolder text-dark">{{ $item->name }}</div>

                                <!--end::Name-->
                                <!--begin::Description-->
                                <p class="text-gray-400 fw-bold fs-5 mt-1 mb-7">{{ $item->description }}</p>
                                <!--end::Description-->
                                <!--begin::Info-->
                                <div class="d-flex flex-wrap mb-1">
                                    <!--begin::Due-->
                                    <div
                                        class="border border-gray-300 border-dashed rounded min-w-125px py-4 px-4 me-7 mb-3">
                                        <div class="fs-6 text-gray-800 fw-bolder">{{ $item->created_at }}</div>

                                    </div>
                                    <div>

                                        @if (auth()->user()->id == $item->user_id)
                                            <div class="border border-gray-300 border-dashed rounded p-1">

                                                <div class="d-flex  ">
                                                    <div class="m-2">
                                                        <a href="{{ route('projects.edit', $item->id) }}"
                                                            class="btn btn btn-dark">Tahrirlash</a>

                                                    </div>
                                                    <div class="m-2">

                                                        <form action="{{ route('projects.destroy', $item->id) }}"
                                                            method="Post" enctype="multipart/form-data">
                                                            @csrf
                                                            @method('DELETE')

                                                            <button onclick="return confirm('Are you sere')"
                                                                class="btn btn-danger ">O'chirish</button>
                                                        </form>
                                                    </div>

                                                </div>
                                            </div>
                                        @endif
                                    </div>

                                </div>






                            </div>
                        </div>

                        </a>


                    </div>
                @endforeach

            </div>
        </div>

    </div>
@endsection